name: Site Monitor

on:
  schedule:
    - cron: '*/30 * * * *'  # Executa a cada 30 minutos
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Versão atualizada

      - name: Set up Python
        uses: actions/setup-python@v4  # Versão atualizada
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run monitor script
        id: monitor
        run: python monitor.py
        env:
          SITES: 'https://www.chili.com.bf,https://chili.pa/,https://chili.com.mx'  # 🔹 Sem espaços após vírgulas!
          MAX_RESPONSE_TIME: '2000'
          GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}  # 🔹 Nome correto da variável

      - name: Notify Google Chat on failure
        if: failure() && steps.monitor.outcome == 'failure'
        run: |
          python -c "
          import os, requests, json
          webhook = os.getenv('GOOGLE_CHAT_WEBHOOK_URL')
          if webhook:
            requests.post(
              webhook,
              json={'text': '⚠️ O monitor de sites detectou problemas!\n\n🔗 Acesse o workflow: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'}
            )
          "
        env:
          GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
