name: Site Monitor

on:
  schedule:
    - cron: '*/30 * * * *'  # Executa a cada 30 minutos
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run monitor script
        id: monitor
        run: |
          python -c "
          import os, requests, json, time

          sites = [url.strip() for url in os.getenv('SITES', '').split(',') if url.strip()]
          webhook_url = os.getenv('GOOGLE_CHAT_WEBHOOK_URL')
          offline_sites = []

          for url in sites:
              try:
                  start = time.time()
                  r = requests.get(url, timeout=10)
                  if r.status_code != 200:
                      offline_sites.append(f'❌ {url} (Status: {r.status_code})')
              except Exception as e:
                  offline_sites.append(f'❌ {url} (Erro: {str(e)})')

          if offline_sites:
              message = '🚨 **Sites Offline**\n\n' + '\n'.join(offline_sites)
              requests.post(webhook_url, json={'text': message})
              exit(1)  # Falha o workflow para acionar a notificação
          "
        env:
          SITES: 'https://www.chili.com.bf,https://chili.pa/,https://chili.com.mx'
          MAX_RESPONSE_TIME: '2000'
          GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}

      - name: Notify Google Chat on failure
        if: failure() && steps.monitor.outcome == 'failure'
        run: |
          echo "Notificação já enviada pelo script Python"
