name: Site Monitor with Discord Alerts

on:
  schedule:
    # Executa a cada 30 minutos
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests discord-webhook
        
    - name: Run monitor script
      id: monitor
      run: python monitor.py
      env:
        SITES: 'https://google.com,https://github.com'  # 🔹 Altere para seus sites!
        MAX_RESPONSE_TIME: '2000'  # Tempo máximo em milissegundos
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        
    - name: Notify Discord on failure
      if: failure() && steps.monitor.outcome == 'failure'
      uses: Ilshidur/action-discord@master
      with:
        args: '⚠️ O monitor de sites detectou problemas! Verifique o workflow.'
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
